### PR TITLE
Removed linear mixin.

### LINKED ISSUE #54: Remove linear mixin
The mixin just obscures what members are on the type, including operator overloads. The mixin also has weird static ifs to prevent overloads on things that it doesn't support, which is exactly backwards.

I'd rather just repeat the correct overloads for each type in the type, not as a template. This also will help IDEs.

Also, `zero` and `one` should be enums.

### PR DESCRIPTION
**Pull request by Kapendev**
Resolves #54 
I was able to compile a project without errors.

### CODE REVIEW

**Comment by Kapendev** [comment]
We could also remove FieldNameTuple from the raymathext.d file if someone wants that.

**Comment by schveiguy** [comment]
Thank you! I'm going to give this some more scrutiny because it's over 400 lines change, but at first glance it looks good.

**Review by schveiguy — APPROVED** [review]
Everything looks good to me.

I believe the inout modifiers should really be const. But I can do that separately.

**Comment by schveiguy** [comment]
> We could also remove FieldNameTuple from the raymathext.d file if someone wants that.

Yes, there is no reason to use it for the functions that are left.

**Pull request merged**
