### PR TITLE
Update to version 4.0.0 according to generating.md doc.

### PR DESCRIPTION
**Pull request by schveiguy**
Ping @ArthaTi if you have a chance to verify. I used your generating.md doc, but of course, raylib 4.0.0 has gotten rid of all the legacy `#define`s so it's even simpler than the instructions say :)

I tested with a simple application and it worked. Let me know if you have any feedback, even if it's to say you don't have time.

Thanks for your previous help!

### CODE REVIEW

**Comment by schveiguy** [comment]
Oh man I thought I broke something, my game was totally broken with its collision reflection. v4.0.0 angles are now ALWAYS IN RADIANS. I can't imagine that being an easy upgrade for anyone!

**Comment by schveiguy** [comment]
Not always in Radians, only math features are in radians. Like Vector2Rotate

**Comment by ArthaTi** [comment]
That's awesome! Seems fine after a quick check but I'm afraid I won't have time to check in "production" this week.

**Comment by schveiguy** [comment]
> Not always in Radians, only math features are in radians. Like Vector2Rotate

Apparently, Vector2Rotate was the only function that was switched to Radians (and it should have been radians before this, it just was missed). Search for uses of that function, and replace with `angle * DEG2RAD`

**Comment by schveiguy** [comment]
Pulling for now. If anyone finds issues, I'll fix that.

**Pull request merged**
